name: Docker test
on: workflow_dispatch
jobs:
  docker-test:
    name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker version
        run: docker --version
      - name: Docker version
        run: sudo systemctl start docker
